#!/usr/bin/perl -w
#
# Plugin to monitor NTP offset value
#
# Parameters understood:
#
# 	config   (required)
#	autoconf
#
# $Id$
#
# Magic markers - optional - used by installation scripts and
# munin-node-configure:
#
#%# family=manual
#%# capabilities=autoconf
#

use strict;
use Net::hostent;
use Socket;

# autoconf - see if this test will work 
if ($ARGV[0] and $ARGV[0] eq "autoconf") {
	`ntpq -c help >/dev/null 2>/dev/null`;
	if ($? eq "0") {
		`ntpq -c rv >/dev/null 2>/dev/null`;
		if ($? eq "0") {
			print "yes\n";
			exit 0;
		} else {
			print "no (unable to determine offset)\n";
			exit 1;
		}
	} else {
		print "no (ntpq not found)\n";
		exit 1;
	}
}

if ($ARGV[0] and $ARGV[0] eq "config") {
	print "graph_title NTP time offset\n";
	print "graph_args --base 1000 --vertical-label msec --upper-limit 1 --lower-limit -1\n";
	print "graph_scale no\n";
	print "offset.label Offset\n";
	print "offset.draw LINE2\n";
	print "hourly_trend.label Hourly Trend\n";
	print "hourly_trend.draw LINE1\n";
	print "hourly_trend.cdef offset,3600,TREND\n";
        exit 0;
}

my @lines = `ntpq -c rv`;
foreach (@lines) {
	next unless /offset/; 
	my $offset = '';
        my @keyvalue = split(/, /, $_);
	foreach (@keyvalue) {
		next unless /^offset/;
		my @value = split(/=/, $_);
		$offset = $value[1];
	}
	print "offset.value $offset\n";
}

exit 0;

# vim:syntax=perl
